language: python

python:
  - "3.5"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# # install Java 8 as required by vnu.jar
# - sudo apt-get update
# - sudo apt-get install oracle-java8-installer
# - sudo update-java-alternatives -s java-8-oracle

install: 
  - "pip install -r requirements.txt"
  - "npm install ."
# - wget "https://github.com/validator/validator/releases/download/16.3.3/vnu.jar_16.3.3.zip"; unzip vnu.jar_16.3.3.zip

before_script:
  - "cd tests/; ./generate_html_for_test_data.sh"

script:
  - "py.test"
# - "java -jar dist/vnu.jar 'output/names.html'"
